## Required binaries
ELIOMC            ?= eliomc
ELIOMOPT          ?= eliomopt
JS_OF_ELIOM       ?= js_of_eliom
ELIOMDEP          ?= eliomdep
PHLUOR_TOOLS	  ?= phluor_tools
# OCSIGENSERVER is defined firstly in the filed written in
# modele_server_conf.txt
# in order to be able to run it on port 80
# These lines are used only if this file don't provide
# these variables
OCSIGENSERVER     ?= ocsigenserver
OCSIGENSERVER.OPT ?= ocsigenserver.opt

## Where to put intermediate object files.
## - ELIOM_{SERVER,CLIENT}_DIR must be distinct
## - ELIOM_CLIENT_DIR must not be the local dir.
## - ELIOM_SERVER_DIR could be ".", but you need to
##   remove it from the "clean" rules...
export ELIOM_SERVER_DIR = _server
export ELIOM_CLIENT_DIR = _client
export ELIOM_TYPE_DIR   = _server
DEPSDIR = _deps
