## Required binaries
ELIOMC            = eliomc
ELIOMOPT          = eliomopt
JS_OF_ELIOM       = js_of_eliom
ELIOMDEP          = eliomdep
OCSIGENSERVER     = ocsigenserver
OCSIGENSERVER.OPT = ocsigenserver.opt
PHLUOR_TOOLS	  = phluor_tools

## Where to put intermediate object files.
## - ELIOM_{SERVER,CLIENT}_DIR must be distinct
## - ELIOM_CLIENT_DIR must not be the local dir.
## - ELIOM_SERVER_DIR could be ".", but you need to
##   remove it from the "clean" rules...
export ELIOM_SERVER_DIR = _server
export ELIOM_CLIENT_DIR = _client
export ELIOM_TYPE_DIR   = _server
DEPSDIR = _deps
